// src/config/menuData.js
export const CATS = [
  {
    key: "BRASAS",
    label: "BRASAS",
    items: [
      { nombre: "POLLO ENTERO", precio: 50 },
      { nombre: "MEDIO POLLO", precio: 28 },
      { nombre: "CUARTO DE POLLO", precio: 17 },
      { nombre: "OCTAVO DE POLLO", precio: 10 },
      { nombre: "MOSTRITO", precio: 12 },
      { nombre: "POLLO BROASTER", precio: 11 },
      { nombre: "CALDO DE GALLINA", precio: 12 }, // simple, no suma brasa
    ],
  },
  {
    key: "PARRILLAS",
    label: "PARRILLAS",
    items: [
      { nombre: "PARRILLA DE POLLO", precio: 13 },
      { nombre: "PARRILLA DE CARNE", precio: 14 },
      { nombre: "CHULETA", precio: 15 },
      { nombre: "ANTICUCHOS", precio: 13 },
      { nombre: "MOLLEJITAS", precio: 13 },
      { nombre: "COMBINADO", precio: 13 },
      { nombre: "MIXTO", precio: 15 },
    ],
  },
  {
    key: "PARRILLAS_ESPECIALES",
    label: "PARRILLAS ESPECIALES",
    items: [
      { nombre: "PARRILLA POLLO + CHORIZO", precio: 15 },
      { nombre: "PARRILLA POLLO + MOLLEJAS", precio: 18 },
      { nombre: "PARRILLA POLLO + COMBINADO", precio: 18 },
      { nombre: "PARRILLA POLLO + ANTICUCHO+CHORIZO", precio: 18 },
      { nombre: "PARRILLA CARNE + CHORIZO", precio: 16 },
      { nombre: "PARRILLA CARNE + MOLLEJAS", precio: 19 },
      { nombre: "PARRILLA CARNE + COMBINADO", precio: 19 },
      { nombre: "PARRILLA CARNE + ANTICUCHO+CHORIZO", precio: 19 },
      { nombre: "PARRILLA CERDO + CHORIZO", precio: 17 },
      { nombre: "PARRILLA CERDO + MOLLEJAS", precio: 20 },
      { nombre: "PARRILLA CERDO + COMBINADO", precio: 20 },
      { nombre: "PARRILLA CERDO + ANTICUCHO+CHORIZO", precio: 20 },
      { nombre: "PARRILLA PEQUEÑA", precio: 30 },
      { nombre: "PARRILLA MEDIANA FAMILIAR", precio: 50 },
      { nombre: "PARRILLA FAMILIAR GIGANTE", precio: 70 },
    ],
  },
  {
    key: "CHIFA",
    label: "CHIFA",
    items: [
      { nombre: "CHAUFA DE POLLO", precio: 14 },
      { nombre: "CHAUFA DE CARNE", precio: 15 },
      { nombre: "CHAUFA DE CHANCHO", precio: 15 },
      { nombre: "CHAUFA MIXTO", precio: 16 },
      { nombre: "AEROPUERTO DE POLLO", precio: 16 },
      { nombre: "AEROPUERTO DE CARNE", precio: 17 },
      { nombre: "AEROPUERTO DE CHANCHO", precio: 17 },
      { nombre: "AEROPUERTO MIXTO", precio: 19 },
      { nombre: "CHIFA COMBINADO DE POLLO", precio: 16 },
      { nombre: "CHIFA COMBINADO DE CARNE", precio: 17 },
      { nombre: "CHIFA COMBINADO DE CHANCHO", precio: 17 },
      { nombre: "CHIFA COMBINADO MIXTO", precio: 19 },
      { nombre: "WANTAN UNIDAD", precio: 1 },
      { nombre: "TORTILLA DE POLLO CON CHAUFA", precio: 15 },
      { nombre: "ALITAS KAYPY", precio: 17 },
      { nombre: "ALITAS CON VERDURAS", precio: 17 },
      { nombre: "CHICHARRON DE ALITAS", precio: 17 },
      { nombre: "ALITAS FRITAS", precio: 16 },
      { nombre: "ALITAS BROASTER", precio: 18 },
      { nombre: "LOMO SALTADO", precio: 16 },
      { nombre: "SOPA WANTAN", precio: 10 },
      { nombre: "SOPA DE VERDURAS", precio: 15 },
    ],
  },
  {
    key: "BEBIDAS",
    label: "BEBIDAS",
    items: [
      { nombre: "INKA PERSONAL VIDRIO", precio: 2 },
      { nombre: "INKA PERSONAL DESC", precio: 4 },
      { nombre: "CONCORDIA PERSONAL", precio: 2 },
      { nombre: "GORDITA", precio: 5 },
      { nombre: "INKA LITRO", precio: 8 },
      { nombre: "PEPSI LITRO", precio: 5 },
      { nombre: "INKA 1.5 LT", precio: 9 },
      { nombre: "CONCORDIA 2 LT", precio: 8 },
      { nombre: "INKA 2 LT", precio: 10 },
      { nombre: "INKA 2.25 LT", precio: 11 },
      { nombre: "JARRA DE CHICHA", precio: 9 },
      { nombre: "JARRA DE MARACUYA", precio: 9 },
      { nombre: "MEDIA JARRA DE CHICHA", precio: 5 },
      { nombre: "MEDIA JARRA DE MARACUYA", precio: 5 },
      { nombre: "VASO DE CHICHA", precio: 3 },
      { nombre: "VASO DE MARACUYA", precio: 3 },
      { nombre: "AGUA MINERAL", precio: 2 },
      { nombre: "VINO", precio: 20 },
    ],
  },
  {
    key: "GUARNICIONES",
    label: "GUARNICIONES",
    items: [
      { nombre: "PORCION DE PAPA DE 3", precio: 3 },
      { nombre: "PORCION DE PAPA DE 5", precio: 5 },
      { nombre: "PORCION DE PAPA DE 10", precio: 10 },
      { nombre: "PORCION DE ARROZ DE 3", precio: 3 },
      { nombre: "PORCION DE ARROZ DE 5", precio: 5 },
      { nombre: "PORCION DE ENSALADA DE 3", precio: 3 },
      { nombre: "PORCION DE ENSALADA DE 5", precio: 5 },
      { nombre: "PORCION DE CHAUFA", precio: 7 },
      { nombre: "PALO DE ANTICUCHO", precio: 4 },
      { nombre: "PORCION MOLLEJA", precio: 8 },
    ],
  },
  {
    key: "OTROS",
    label: "OTROS",
    items: [
      { nombre: "TAPER", precio: 1 },
      { nombre: "CREMA", precio: 1 },
    ],
  },
];
